stages:
  - build
  - deploy

build_project_amd64_release:
  stage: build
  image: rust
  script:
    - cargo build -r
  artifacts:
    paths:
      - target/release/passwordgenerator-rs_amd64

release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'