on: [push]
jobs:
  checkout-and-build:
    runs-on: node-lts-trixie
    container:
      image: rust
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build project
        run: cargo build -v